#ifndef __WB_CONST_H__
#define __WB_CONST_H__

#include <Arduino.h>

//tunings

//Really traveled distance > thought traveled distance -> decrease codewheels radius
//Really rotated angle > thought rotated angle         -> increase axle track
//Turn right when thinking moving forward              -> increase left codewheel radius
//Turn left when thinking moving forward               -> increase right codewheel radius

#define LEFTWHEEL_RADIUS_VALUE 23.8125
#define LEFTWHEEL_CONSTANT_VALUE 0.209380534
#define LEFTWHEEL_MAXPWM_VALUE 1.0
#define RIGHTWHEEL_RADIUS_VALUE 23.8125
#define RIGHTWHEEL_CONSTANT_VALUE 0.209380534
#define RIGHTWHEEL_MAXPWM_VALUE 1.0

#define LEFTCODEWHEEL_COUNTSPERREV_VALUE -(10000/2)//TODO: Fix/source problem this /2
#define RIGHTCODEWHEEL_COUNTSPERREV_VALUE (10000/2)
#define LEFTCODEWHEEL_RADIUS_VALUE 22.78
#define RIGHTCODEWHEEL_RADIUS_VALUE 22.767

#define ODOMETRY_AXLETRACK_VALUE 209.7622878807068
#define ODOMETRY_SPLIPPAGE_VALUE 0

#define VELOCITYCONTROL_AXLETRACK_VALUE 125.0//201.5
#define VELOCITYCONTROL_MAXLINACC_VALUE 500
#define VELOCITYCONTROL_MAXLINDEC_VALUE 1000
#define VELOCITYCONTROL_MAXANGACC_VALUE 3.14
#define VELOCITYCONTROL_MAXANGDEC_VALUE 6.28
#define VELOCITYCONTROL_SPINSHUTDOWN_VALUE 0

/*---- LINEAR VELOCITIES PID  ----*/
#define LINVELPID_KP_VALUE 1.85
#define LINVELPID_KI_VALUE 35.0
#define LINVELPID_KD_VALUE 0.0

#define LINVELPID_MINOUTPUT_VALUE -1000
#define LINVELPID_MAXOUTPUT_VALUE 1000

/*---- ANGULAR VELOCITIES PID ----*/
#define ANGVELPID_KP_VALUE 3
#define ANGVELPID_KI_VALUE 15.0
#define ANGVELPID_KD_VALUE 0.0

#define ANGVELPID_MINOUTPUT_VALUE -18.0278/2
#define ANGVELPID_MAXOUTPUT_VALUE 18.0278/2

/*---- POSITION PID ----*/
#define POSITIONCONTROL_LINVELKP_VALUE 2.2
#define POSITIONCONTROL_ANGVELKP_VALUE 2.5

#define POSITIONCONTROL_LINVELMAX_VALUE 700
#define POSITIONCONTROL_ANGVELMAX_VALUE 10
#define POSITIONCONTROL_LINPOSTHRESHOLD_VALUE 6
#define POSITIONCONTROL_ANGPOSTHRESHOLD_VALUE 0.10000000149011612
#define PUREPURSUIT_LOOKAHEAD_VALUE 100.0 //  TODO 235 valeur relle a remettre apres la coupe
#define PUREPURSUIT_LOOKAHEADBIS_VALUE 100.0 //ODO 200 valeur relle a remettre apres la coupe

// Timesteps
#define ODOMETRY_TIMESTEP         20e-3 // s
#define PID_CONTROLLERS_TIMESTEP  20e-3 // s
#define POSITIONCONTROL_TIMESTEP  20e-3 // s

// DC motors driver
#define LEFT_MOTOR_EN    PB13
#define LEFT_MOTOR_PWM  PE11
#define LEFT_MOTOR_DIR   PF4
#define RIGHT_MOTOR_EN   PB15
#define RIGHT_MOTOR_PWM PE9
#define RIGHT_MOTOR_DIR PF5
#define DRIVER_RESET    PA15
#define DRIVER_FAULT    PB12

// Codewheel
//Voir le setup des encoedeurs pour les constantes

#endif // __WB_CONST_H__
