#ifndef __WB_CONST_H__
#define __WB_CONST_H__

#include <Arduino.h>

//tunings

//Really traveled distance > thought traveled distance -> decrease codewheels radius
//Really rotated angle > thought rotated angle         -> increase axle track
//Turn right when thinking moving forward              -> increase left codewheel radius
//Turn left when thinking moving forward               -> increase right codewheel radius

#define LEFTWHEEL_RADIUS_VALUE 23.8125
#define LEFTWHEEL_CONSTANT_VALUE 0.209380534
#define LEFTWHEEL_MAXPWM_VALUE 1
#define RIGHTWHEEL_RADIUS_VALUE 23.8125
#define RIGHTWHEEL_CONSTANT_VALUE 0.209380534
#define RIGHTWHEEL_MAXPWM_VALUE 1

#define LEFTCODEWHEEL_COUNTSPERREV_VALUE 10000
#define RIGHTCODEWHEEL_COUNTSPERREV_VALUE -10000
#define LEFTCODEWHEEL_RADIUS_VALUE 22.78
#define RIGHTCODEWHEEL_RADIUS_VALUE 22.767

#define ODOMETRY_AXLETRACK_VALUE 209.7622878807068
#define ODOMETRY_SPLIPPAGE_VALUE 0

#define VELOCITYCONTROL_AXLETRACK_VALUE 125.0//201.5
#define VELOCITYCONTROL_MAXLINACC_VALUE 500.0
#define VELOCITYCONTROL_MAXLINDEC_VALUE 1000
#define VELOCITYCONTROL_MAXANGACC_VALUE 3.14
#define VELOCITYCONTROL_MAXANGDEC_VALUE 6.28
#define VELOCITYCONTROL_SPINSHUTDOWN_VALUE 1

/*---- LINEAR VELOCITIES PID  ----*/
#define LINVELPID_KP_VALUE 1.85
#define LINVELPID_KI_VALUE 35.0
#define LINVELPID_KD_VALUE 0.0

#define LINVELPID_MINOUTPUT_VALUE -1000
#define LINVELPID_MAXOUTPUT_VALUE 1000

/*---- ANGULAR VELOCITIES PID ----*/
#define ANGVELPID_KP_VALUE 3
#define ANGVELPID_KI_VALUE 15.0
#define ANGVELPID_KD_VALUE 0.0

#define ANGVELPID_MINOUTPUT_VALUE -18.0278
#define ANGVELPID_MAXOUTPUT_VALUE 18.0278

/*---- POSITION PID ----*/
#define POSITIONCONTROL_LINVELKP_VALUE 2.2
#define POSITIONCONTROL_ANGVELKP_VALUE 2.5

#define POSITIONCONTROL_LINVELMAX_VALUE 700
#define POSITIONCONTROL_ANGVELMAX_VALUE 10
#define POSITIONCONTROL_LINPOSTHRESHOLD_VALUE 3
#define POSITIONCONTROL_ANGPOSTHRESHOLD_VALUE 0.10000000149011612
#define PUREPURSUIT_LOOKAHEAD_VALUE 235.0
#define PUREPURSUIT_LOOKAHEADBIS_VALUE 200.0

//Adresses
#define LEFTWHEEL_ADDRESS           0x040 //  8 bytes
#define RIGHTWHEEL_ADDRESS          0x060 //  8 bytes
#define LEFTCODEWHEEL_ADDRESS       0x080 //  8 bytes
#define RIGHTCODEWHEEL_ADDRESS      0x0A0 //  8 bytes
#define ODOMETRY_ADDRESS            0x0C0 //  4 bytes
#define VELOCITYCONTROL_ADDRESS     0x100 // 20 bytes
#define LINVELPID_ADDRESS		    0x140 // 20 bytes
#define ANGVELPID_ADDRESS           0x180 // 20 bytes
#define POSITIONCONTROL_ADDRESS     0x200 // 16 bytes
#define PUREPURSUIT_ADDRESS         0x240 //  4 bytes
#define SMOOTHTRAJECTORY_ADDRESS    0x280 //  4 bytes

// Timesteps
#define ODOMETRY_TIMESTEP         20e-3 // s
#define PID_CONTROLLERS_TIMESTEP  20e-3 // s
#define POSITIONCONTROL_TIMESTEP  50e-3 // s

// DC motors driver
//TODO: Redo pinout
#define LEFT_MOTOR_EN    6
#define LEFT_MOTOR_PWM   3
#define LEFT_MOTOR_DIR   5
#define RIGHT_MOTOR_EN   9
#define RIGHT_MOTOR_PWM 11
#define RIGHT_MOTOR_DIR 10
#define DRIVER_RESET    12
#define DRIVER_FAULT    A7

// Codewheel
//Voir le setup des encoedeurs pour les constantes

#endif // __WB_CONST_H__
