var annotated_dup =
[
    [ "HazelnutGripper", "d2/d51/namespaceHazelnutGripper.html", [
      [ "AbstractAbsoluteEncoder", "d1/de1/classHazelnutGripper_1_1AbstractAbsoluteEncoder.html", "d1/de1/classHazelnutGripper_1_1AbstractAbsoluteEncoder" ],
      [ "BournsACEncoder", "d8/d86/classHazelnutGripper_1_1BournsACEncoder.html", "d8/d86/classHazelnutGripper_1_1BournsACEncoder" ],
      [ "ColorData", "d6/d6e/structHazelnutGripper_1_1ColorData.html", "d6/d6e/structHazelnutGripper_1_1ColorData" ],
      [ "Gripper", "d4/dcb/classHazelnutGripper_1_1Gripper.html", null ],
      [ "GripperFinger", "d6/d59/classHazelnutGripper_1_1GripperFinger.html", "d6/d59/classHazelnutGripper_1_1GripperFinger" ]
    ] ],
    [ "AbstractAbsoluteEncoder", "d4/ddc/classAbstractAbsoluteEncoder.html", "d4/ddc/classAbstractAbsoluteEncoder" ],
    [ "AX12", "d8/d27/classAX12.html", "d8/d27/classAX12" ],
    [ "Block_header", "dc/da5/unionBlock__header.html", null ],
    [ "BournsACEncoder", "d0/d04/classBournsACEncoder.html", "d0/d04/classBournsACEncoder" ],
    [ "BrushlessMotor", "d7/d82/classBrushlessMotor.html", "d7/d82/classBrushlessMotor" ],
    [ "Buttons", "dc/d2e/classButtons.html", null ],
    [ "Clock", "df/d45/classClock.html", "df/d45/classClock" ],
    [ "Color", "d0/da2/structColor.html", null ],
    [ "CRC16", "db/d6d/classCRC16.html", null ],
    [ "DynamixelClass", "df/dc5/classDynamixelClass.html", null ],
    [ "Elevator", "d9/db0/classElevator.html", "d9/db0/classElevator" ],
    [ "EndStop", "df/d5b/classEndStop.html", "df/d5b/classEndStop" ],
    [ "FullSpeedServo", "d9/df7/classFullSpeedServo.html", "d9/df7/classFullSpeedServo" ],
    [ "LedButton", "d8/d45/classLedButton.html", null ],
    [ "Logger", "db/d67/classLogger.html", "db/d67/classLogger" ],
    [ "Musique", "d6/da1/classMusique.html", "d6/da1/classMusique" ],
    [ "NonCopyable", "dc/d3c/classNonCopyable.html", null ],
    [ "ObjectDetector", "d6/dd4/classObjectDetector.html", "d6/dd4/classObjectDetector" ],
    [ "PeriodicProcess", "d2/dfa/classPeriodicProcess.html", "d2/dfa/classPeriodicProcess" ],
    [ "Point", "d8/d43/structPoint.html", null ],
    [ "SensorArray", "de/d4b/classSensorArray.html", "de/d4b/classSensorArray" ],
    [ "ShiftRegister", "de/ded/classShiftRegister.html", null ],
    [ "StepByStepMotor", "d9/dd4/classStepByStepMotor.html", null ],
    [ "STM32HALTimer", "d8/dd9/classSTM32HALTimer.html", null ],
    [ "VL53L5CX", "d9/d0e/classVL53L5CX.html", "d9/d0e/classVL53L5CX" ],
    [ "VL53L5CX_Configuration", "da/dce/structVL53L5CX__Configuration.html", null ],
    [ "VL53L5CX_Platform", "de/d5c/structVL53L5CX__Platform.html", null ],
    [ "VL53L5CX_ResultsData", "d4/d7d/structVL53L5CX__ResultsData.html", null ]
];