; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = nucleo_h723zg_BreizhBot

[env:nucleo_h723zg_BreizhBot]
build_src_filter =
	+<*>
	+<**/*>
	-<decisions/Decisions.*>
platform = ststm32
board = nucleo_h723zg
framework = arduino
lib_ldf_mode = chain+
lib_deps =
;	https://github.com/stm32duino/STM32FreeRTOS.git
	adafruit/Adafruit PWM Servo Driver Library@^3.0.2
	adafruit/Adafruit BusIO@^1.17.0
	arduino-libraries/LiquidCrystal@^1.0.7
	lib/Grafcet
	lib/Wheeledbase
;	https://github.com/stm32duino/VL53L5CX.git

monitor_speed = 921600
monitor_raw = yes
build_flags =
  -std=gnu++23
	-std=gnu2x
	-D LCD_OUTPUT=1
	-D LED_BUILTIN=PB15
	-D ENABLE_HWSERIAL6
	-D PIO_FRAMEWORK_ARDUINO_NANOLIB_FLOAT_PRINTF
build_unflags =
	-std=gnu++17
	-std=gnu17
check_flags = '--checks=-*'
check_src_filters =
  +<src/*>
  +<lib/*>
  -<lib/STM32duino FreeRTOS/**/*>
  -<.pio/**/*>
  -<lib/TraceRecorder/**/*>
  -<**/cmake-build-debug/**>
build_type = debug
check_tool = clangtidy
check_skip_packages = yes

[env:nucleo_f072rb_TEST]
platform = ststm32
board = nucleo_f072rb
framework = arduino
lib_deps =
;	https://github.com/stm32duino/STM32FreeRTOS.git
	adafruit/Adafruit PWM Servo Driver Library@^3.0.2

[env:nucleo_f072rb_checks]
build_src_filter =
	+<*>
	+<**/*>
	-<decisions/Decisions.*>
platform = ststm32
board = nucleo_h723zg
framework = arduino
lib_deps =
;	https://github.com/stm32duino/STM32FreeRTOS.git
	adafruit/Adafruit PWM Servo Driver Library@^3.0.2
	adafruit/Adafruit BusIO@^1.17.0
;	https://github.com/stm32duino/VL53L5CX.git
	Wire
monitor_speed = 115200
monitor_raw = yes
build_flags =
	-D ENABLE_HWSERIAL6
	-D PIO_FRAMEWORK_ARDUINO_NANOLIB_FLOAT_PRINTF
build_type = debug
check_tool = cppcheck
check_flags = --enable=all
check_skip_packages = yes
