name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - uses: actions/checkout@v4
        # You may pin to the exact commit or the version.
        # uses: langroodi/doxygenize@7678ae6c3ab3dd9c039a1f814c9bb00ecc17cc17
        - uses: langroodi/doxygenize@v1.7.1
          with:
          # Doxygen configuration file path
            doxygenconf: ./doc/Doxyfile # default is ./Doxyfile
          # Generated HTML documents output folder
            htmloutput: ./html
                
